### ISSUE TITLE
скрапінг елементів, які генерує javascript

### ISSUE THREAD

**Issue by Myralllka** [Nazarii/product_catalog#1]
Вітаю! мене зацікавила ця тема після Вашого воркшопу, і я пробую в ній розібратися. довго й нудно намагався знайти патерни на цьому сайті(https://tables.finance.ua/ua/credit_deposit/deposit#app-tabloid/client=nat&currency=USD&sort=0.1), поки не зрозумів - елементи, які я маю скрапити, підтягує JS. Це є інформація про депозити, а саме відсоткові ставки, періоди. Буду дуже вдячний за підказку, як розібратися в цьому питанні

**Comment by Nazarii** [comment]
Привіт,
В кінцевому результаті інфа береться і обробляється JS [звідси](https://resources.finance.ua/ua/deposit/program?type=nat) Спробуй розпарсати і відсортувати звідси дані. Як варіант можна пробувати завантаження через selenium, але так виглядає простіше.

**Comment by Myralllka** [comment]
добре, велике спасибі!
